export enum Poste{
  PREMIERELIGNE = 'PREMIERELIGNE',
  DEUXIEMELIGNE = 'DEUXIEMELIGNE',
  TROISIEMELIGNE = 'TROISIEMELIGNE',
  DEMIMELEE = 'DEMIMELEE',
  DEMIOUVERTURE = 'DEMIOUVERTURE',
  TROISQUARTSCENTRE = 'TROISQUARTSCENTRE',
  AILIERS = 'AILIERS',
  ARRIÈRE = 'ARRIÈRE',
}
